---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: 'wh'
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here for Lua or Lmod,
#       please make sure to add corresponding values in group_vars/all/*.yml
#
lua_version: '5.4.6'
luaposix_version: '36.2.1'
lmod_version: '8.7.32'
easybuild_version: '5.1.2'
eb_user: umcg-envsync
eb_group: umcg-depad
group_module_versions:
  umcg-gd:
    NGS_Automated:
      default: 4.3.1
    NGS_DNA: 4.2.2
    ConcordanceCheck: 3.0.0
    ngs-utils: 24.03.1
    NGS_Demultiplexing: 2.5.4
    Trendanalysis: 2.1.0
    vip: 9.2.0
  umcg-gap:
    NGS_Automated:
      default: 4.3.1
    GAP: 2.7.0
    AGCT: 1.3.0
    ngs-utils: 24.03.1
  umcg-genomescan:
    NGS_Automated:
      default: 4.3.1
    nf_ngs_dna: 1.1.0
    NGS_RNA: 4.1.2
    NGS_DNA: 4.2.2
    ngs-utils: 24.03.1
  umcg-atd:
    NGS_Automated:
      default: 4.3.1  # Default NGS_Automated version.
      NGS_DNA: beta  # Overruling NGS_Automated version for NGS_Automated-NGS_DNA bundles.
    NGS_DNA: 4.2.2
    ConcordanceCheck: 3.0.0
    ngs-utils: 24.02.2
    NGS_Demultiplexing: 2.5.4
    Trendanalysis: 2.1.0
  umcg-gsad:
    NGS_Automated:
      default: 4.3.1
    GAP: 2.7.0
    AGCT: 1.3.0
    ngs-utils: 24.03.1
  umcg-gst:
    NGS_Automated:
      default: 4.3.1
    nf_ngs_dna: 1.1.0
    NGS_DNA: 4.2.2
    NGS_RNA: 4.1.2
    ngs-utils: 24.03.1
  umcg-labgnkbh:
    NGS_Automated:
      default: 4.2.0
    ngs-utils: 24.03.1
    NGS_Demultiplexing: 2.5.4
  umcg-patho:
    NGS_Automated:
      default: 4.2.0
    ngs-utils: 24.03.1
  # umcg-pr:
  #   NGS_Automated:
  #     default: 4.1.0
  #   ngs-utils: 24.02.2
  umcg-lab:
    NGS_Automated:
      default: 4.3.0
  umcg-pgx:
    NGS_Automated:
      default: 4.7.0
    AGCT: 1.3.0
    PGx: 2.1.0
#
# Sources, software and reference data to install/fetch.
#
public_sources: [
]
private_sources: []
refdata: [
  'GRC/Hg19toHumanG1kV37.chain',
  'dbSNP',
  '1000G',
  'Agilent',
  'CGD',
  'ClinVar',
  'Controls_Convading_XHMM',
  'GSAarray',
  'Ensembl',
  'Prepkits',
  'ExAC',
  'ManVarList',
  'gnomAD/release-170228',
  'GAVIN',
  'UMCG',
  'gonl',
  'inSilico',
  'snpEff-4.3',
]
static_easyconfigs:
  - 'c/cluster-utils/cluster-utils-v26.01.1-GCCcore-13.3.0.eb'
  - 'd/depad-utils/depad-utils-v26.04.3.eb'
chaperone_only_easyconfigs: "{{ all_easyconfigs | select('search', '(NGS_Automated-.*-bare|depad-utils-.*).eb') | list }}"
...
