---
#
# Defaults for group variables.
# Convention for variable names: lowercase and underscore separated.
#
MODE_2775_HARD: 'u=rwx,g=rwxs,o=rx'
MODE_2770_HARD: 'u=rwx,g=rwxs,o='
MODE_2750_HARD: 'u=rwx,g=rxs,o='
MODE_0775_HARD: 'u=rwx,g=rwx,o=rx'
MODE__775_SOFT: 'u+rwX,g+rwX,o+rX,o-w'
MODE_0664_HARD: 'u=rw,g=rw,o=r'
MODE_D2775_F0664: 'Du=rwx,Dg=rwxs,Do=rx,Fu=rw,Fg=rw,Fo=r'
hpc_env_prefix: '/apps'
hpc_groups_prefix: '/groups'
easybuild_sources_dir: "{{ hpc_env_prefix }}/sources/"
easybuild_modules_dir: "{{ hpc_env_prefix }}/modules/"
easybuild_software_dir: "{{ hpc_env_prefix }}/software/"
easybuild_modules_syntax: 'Lua'
extra_easyconfigs_version: 1.0
extra_easyconfigs_repository: 'take-it-easyconfigs'
extra_easyconfigs_prefix: "{{ easybuild_software_dir }}/easyconfigs/{{ extra_easyconfigs_repository }}-{{ extra_easyconfigs_version }}/"
remote_env_cache_server: "ssh.webhosting.rug.nl"
remote_env_cache_user: "f114592"
remote_env_cache_dir_public:  '{{ remote_env_cache_user }}@{{ remote_env_cache_server }}:site/apps/'
remote_env_cache_dir_private: '{{ remote_env_cache_user }}@{{ remote_env_cache_server }}:rsync-only/apps/'
configure_env_in_cronjob: 'export SOURCE_HPC_ENV="True"; . ~/.bashrc'
#
# Lua & Lmod vars by version.
#
lua_releases:
  5.1.4.9:
    url: 'http://sourceforge.net/projects/lmod/files/lua-5.1.4.9.tar.bz2/download'
    checksum: 'md5:a8d0443fe79fc4e9aaded057d81304cd'
  5.4.6:
    url: 'https://www.lua.org/ftp/lua-5.4.6.tar.gz'
    checksum: 'sha256:7d5ea1b9cb6aa0b59ca3dde1c6adcb57ef83a1ba8e5432c0ecd06bf439b3ad88'
luaposix_releases:
  36.2.1:
    url: 'https://github.com/luaposix/luaposix/archive/refs/tags/v36.2.1.tar.gz'
    checksum: 'sha256:44e5087cd3c47058f9934b90c0017e4cf870b71619f99707dd433074622debb1'
lmod_releases:
  6.1.3:
    url: 'https://github.com/TACC/Lmod/archive/6.1.3.tar.gz'
    checksum: 'md5:a2ea3c83f08d4175f08f84ac2a9bd508'
  7.8.8:
    url: 'https://github.com/TACC/Lmod/archive/7.8.8.tar.gz'
    checksum: 'md5:a0a7c808081e3d6ea021bc0c47fd373a'
  8.6.2:
    url: 'https://github.com/TACC/Lmod/archive/8.6.2.tar.gz'
    checksum: 'sha256:2851a4bcbf1d853220f36fb76931f62a4422bf6c626297f6c17fc7c05393ea20'
  8.7.32:
    url: 'https://github.com/TACC/Lmod/archive/8.7.32.tar.gz'
    checksum: 'sha256:727df3dafb634749947418b334a0828d63753c38f02d4d7a27c6c507e9512d3b'
#
# Vars for certain analysis and groups.
#
analysis_folders:
  AGCT:
    tmp:
      - generatedscripts
      - generatedscripts/AGCT
      - logs
      - runs
      - runs/AGCT
      - rawdata
      - rawdata/array
      - rawdata/array/IDAT
      - rawdata/array/GTC
      - Samplesheets
      - Samplesheets/AGCT
      - Samplesheets/archive
      - tmp
      - tmp/AGCT
    dat:
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - concordance
      - concordance/array
      - logs
      - rawdata
      - rawdata/array
      - rawdata/array/IDAT
      - rawdata/array/GTC
      - Samplesheets
      - Samplesheets/archive
  GAP:
    tmp:
      - DiagnosticOutput
      - generatedscripts
      - generatedscripts/GAP
      - logs
      - projects
      - projects/GAP
      - rawdata
      - rawdata/array
      - rawdata/array/IDAT
      - rawdata/array/GTC
      - Samplesheets
      - Samplesheets/GAP
      - Samplesheets/archive
      - tmp
      - tmp/GAP
    dat:
      - DiagnosticOutput
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - concordance
      - concordance/array
      - logs
      - projects
      - rawdata
      - rawdata/array
      - rawdata/array/IDAT
      - rawdata/array/GTC
      - Samplesheets
      - Samplesheets/archive
  ConcordanceCheck:
    tmp:
      - concordance
      - concordance/array
      - concordance/jobs
      - concordance/logs
      - concordance/ngs
      - concordance/results
      - concordance/samplesheets
      - concordance/samplesheets/archive
      - concordance/tmp
    dat:
      - ConcordanceCheckOutput
      - ConcordanceCheckSamplesheets
      - ConcordanceCheckSamplesheets/archive
      - ConcordanceCheckSamplesheets/jobfiles_v3
      - ConcordanceCheckSamplesheets/jobfiles_v3/archive
    prm:
      - concordance
      - concordance/logs
      - concordance/results
      - concordance/verificatieValidatieOutput
  GsRawData:
    tmp:
      - logs
      - rawdata
      - rawdata/ngs
      - runs
      - Samplesheets
      - Samplesheets/archive
      - tmp
    dat:
      - logs
      - samplesheets
      - samplesheets/new
  GsAnalysisData:
    tmp:
      - generatedscripts
      - generatedscripts/DRAGEN
      - logs
      - projects
      - projects/DRAGEN
      - rawdata
      - rawdata/ngs
      - Samplesheets
      - Samplesheets/DRAGEN
      - tmp
      - tmp/DRAGEN
    dat:
      - samplesheets
      - samplesheets/new
  BclDataToPrm:
    tmp:
      - logs
      - Samplesheets
      - Samplesheets/archive
    dat:
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - logs
      - rawdata
      - rawdata/bcls
  nf_ngs_dna:
    tmp:
      - logs
      - projects
      - projects/DRAGEN
      - projects/POST_DRAGEN
      - rawdata
      - rawdata/ngs
      - Samplesheets
      - Samplesheets/archive
      - Samplesheets/DRAGEN
      - Samplesheets/POST_DRAGEN
      - results
    dat:
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - logs
      - projects
      - Samplesheets
      - Samplesheets/archive
  NGS_Demultiplexing:
    tmp:
      - generatedscripts
      - generatedscripts/NGS_Demultiplexing
      - logs
      - rawdata
      - rawdata/ngs
      - runs
      - runs/NGS_Demultiplexing
      - Samplesheets
      - Samplesheets/archive
      - Samplesheets/NGS_Demultiplexing
      - tmp
      - tmp/NGS_Demultiplexing
    dat:
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - logs
      - rawdata
      - rawdata/ngs
      - Samplesheets
      - Samplesheets/archive
  NGS_DNA:
    tmp:
      - generatedscripts
      - generatedscripts/NGS_DNA
      - logs
      - logs/concordance
      - projects
      - projects/NGS_DNA
      - rawdata
      - rawdata/ngs
      - Samplesheets
      - Samplesheets/archive
      - Samplesheets/NGS_DNA
      - tmp
      - tmp/NGS_DNA
    dat:
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - logs
      - projects
      - Samplesheets
      - Samplesheets/archive
  NGS_RNA:
    tmp:
      - generatedscripts
      - generatedscripts/NGS_RNA
      - logs
      - logs/concordance
      - projects
      - projects/NGS_RNA
      - rawdata
      - rawdata/ngs
      - Samplesheets
      - Samplesheets/archive
      - Samplesheets/NGS_RNA
      - tmp
      - tmp/NGS_RNA
    dat:
      - logs
      - samplesheets
      - samplesheets/new
    prm:
      - logs
      - projects
      - rawdata
      - rawdata/ngs
      - Samplesheets
      - Samplesheets/archive
  trendanalysis:
    tmp:
      - trendanalysis
      - trendanalysis/darwin
      - trendanalysis/dragen
      - trendanalysis/ogm
      - trendanalysis/ogm/metricsFinished
      - trendanalysis/ogm/metricsInput
      - trendanalysis/openarray
      - trendanalysis/projects
      - trendanalysis/database
      - trendanalysis/rawdata
      - trendanalysis/reports
      - trendanalysis/RNAprojects
      - trendanalysis/tmp
    dat:
      - trendanalysis
      - trendanalysis/archive
      - trendanalysis/logs
    prm:
      - trendanalysis
      - trendanalysis/reports
notification_targets:
  hpc-helpdesk:
    notification_webhooks:
      - "{{ vault_webhooks['hpc-helpdesk'] }}"
  hpc-helpdesk_and_gd-ngs-dataverwerking:
    notification_webhooks:
      - "{{ vault_webhooks['hpc-helpdesk'] }}"
      - "{{ vault_webhooks['gd-ngs-dataverwerking'] }}"
  hpc-helpdesk_and_gd-array-dataverwerking:
    notification_webhooks:
      - "{{ vault_webhooks['hpc-helpdesk'] }}"
      - "{{ vault_webhooks['gd-array-dataverwerking'] }}"
  hpc-helpdesk_and_labgnkbh:
    notification_webhooks:
      - "{{ vault_webhooks['hpc-helpdesk'] }}"
      - "{{ vault_webhooks['labgnkbh'] }}"
  hpc-helpdesk_and_patho:
    notification_webhooks:
      - "{{ vault_webhooks['hpc-helpdesk'] }}"
      - "{{ vault_webhooks['patho'] }}"
  hpc-helpdesk_and_pr:
    notification_webhooks:
      - "{{ vault_webhooks['hpc-helpdesk'] }}"
      - "{{ vault_webhooks['pr'] }}"
dynamic_easyconfigs: >-
  {%- set easyconfigs_for_group_modules = [] %}
  {%- if group_module_versions is defined %}
    {%- for group, modules in group_module_versions.items() %}
      {%- for software, version in modules.items() %}
        {%- if software == 'NGS_Automated' %}
          {%- set easyconfigs_for_group_modules = easyconfigs_for_group_modules.append(
                'n/NGS_Automated/NGS_Automated-' + version + '-bare.eb'
              ) %}
        {%- elif software == 'NGS_DNA' or software == 'GAP' or software == 'NGS_Demultiplexing' or software == 'AGCT' %}
          {%- set easyconfigs_for_group_modules = easyconfigs_for_group_modules.append(
                'n/NGS_Automated/NGS_Automated-' + group_module_versions[group]['NGS_Automated'] + '-' + software + '-' + version + '.eb'
              ) %}
        {%- else %}
          {%- set easyconfigs_for_group_modules = easyconfigs_for_group_modules.append(
                software[0:1] | lower + '/' + software + '/' + software + '-' + version + '.eb'
              ) %}
        {%- endif %}
      {%- endfor %}
    {%- endfor %}
  {%- endif %}
  {{- easyconfigs_for_group_modules | default([]) -}}
all_easyconfigs: "{{ dynamic_easyconfigs | default([]) | union(static_easyconfigs | default([])) }}"
easyconfigs: "{{ all_easyconfigs }}"
...
