---
#
# Symlinks to enable sending notifications to certain target when notification are enabled for an analysis phase in NGS_Automated.
#
group_notification_targets:
  ######################################################################################################################
  # umcg-atd group
  ######################################################################################################################
  - group: umcg-atd
    lfs: tmp05
    user: umcg-atd-ateambot
    type: notification_webhooks
    analysis_phases: [startPipeline, ConcordanceCheck, pipeline, calculateProjectMd5s, startNanoporePipeline]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: tmp15
    user: umcg-atd-ateambot
    type: notification_webhooks
    analysis_phases: [startPipeline, ConcordanceCheck, pipeline, calculateProjectMd5s, startNanoporePipeline, startInhouseDragenPipeline]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: dat05
    user: umcg-atd-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-atd
    lfs: prm05
    user: umcg-atd-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToPrm, copyRawDataToTmp, copyProjectDataToPrm, copyRawNanoporeDataToPrm, copyRawNanoporeDataToTmp, checkRawdata]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gd group
  ######################################################################################################################
  - group: umcg-gd
    lfs: tmp05
    user: umcg-gd-ateambot
    type: notification_webhooks
    analysis_phases: [startPipeline, ConcordanceCheck, calculateProjectMd5s, startNanoporePipeline]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: tmp15
    user: umcg-gd-ateambot
    type: notification_webhooks
    analysis_phases: [startPipeline, ConcordanceCheck, calculateProjectMd5s, startNanoporePipeline, startInhouseDragenPipeline]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: tmp05
    user: umcg-gd-ateambot
    type: notification_webhooks
    analysis_phases: [pipeline]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: tmp15
    user: umcg-gd-ateambot
    type: notification_webhooks
    analysis_phases: [pipeline]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: dat05
    user: umcg-gd-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gd
    lfs: prm05
    user: umcg-gd-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToTmp, copyRawNanoporeDataToPrm, copyRawNanoporeDataToTmp, checkRawdata]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gd
    lfs: prm05
    user: umcg-gd-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToPrm, copyProjectDataToPrm]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gsad group
  ######################################################################################################################
  - group: umcg-gsad
    lfs: tmp05
    user: umcg-gsad-ateambot
    type: notification_webhooks
    analysis_phases: [arrayConversion, startPipeline, pipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gsad
    lfs: tmp15
    user: umcg-gsad-ateambot
    type: notification_webhooks
    analysis_phases: [arrayConversion, startPipeline, pipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gsad
    lfs: dat05
    user: umcg-gsad-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gsad
    lfs: prm05
    user: umcg-gsad-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToPrm, copyRawDataToTmp, copyProjectDataToPrm]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gap group
  ######################################################################################################################
  - group: umcg-gap
    lfs: tmp05
    user: umcg-gap-ateambot
    type: notification_webhooks
    analysis_phases: [startPipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gap
    lfs: tmp15
    user: umcg-gap-ateambot
    type: notification_webhooks
    analysis_phases: [startPipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gap
    lfs: tmp05
    user: umcg-gap-ateambot
    type: notification_webhooks
    analysis_phases: [arrayConversion, pipeline]
    notification_target: hpc-helpdesk_and_gd-array-dataverwerking
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gap
    lfs: tmp15
    user: umcg-gap-ateambot
    type: notification_webhooks
    analysis_phases: [arrayConversion, pipeline]
    notification_target: hpc-helpdesk_and_gd-array-dataverwerking
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gap
    lfs: dat05
    user: umcg-gap-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk_and_gd-array-dataverwerking
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gap
    lfs: prm05
    user: umcg-gap-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToTmp]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gap
    lfs: prm05
    user: umcg-gap-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToPrm, copyProjectDataToPrm]
    notification_target: hpc-helpdesk_and_gd-array-dataverwerking
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gst group
  ######################################################################################################################
  - group: umcg-gst
    lfs: tmp05
    user: umcg-gst-ateambot
    type: notification_webhooks
    analysis_phases: [PullAndProcessGsRawData, PullGsAnalysisData, ProcessGsAnalysisData, startDragenPipeline, startPostDragenPipeline, pipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gst
    lfs: tmp15
    user: umcg-gst-ateambot
    type: notification_webhooks
    analysis_phases: [PullAndProcessGsRawData, PullGsAnalysisData, ProcessGsAnalysisData, startDragenPipeline, startPostDragenPipeline, pipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gst
    lfs: dat05
    user: umcg-gst-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-genomescan group
  ######################################################################################################################
  - group: umcg-genomescan
    lfs: tmp05
    user: umcg-genomescan-ateambot
    type: notification_webhooks
    analysis_phases: [startDragenPipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: tmp15
    user: umcg-genomescan-ateambot
    type: notification_webhooks
    analysis_phases: [startDragenPipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: tmp05
    user: umcg-genomescan-ateambot
    type: notification_webhooks
    analysis_phases: [PullAndProcessGsRawData, PullGsAnalysisData, ProcessGsAnalysisData, startDragenPipeline, startPipeline, startPostDragenPipeline, startNextflowDragenPipeline, pipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: tmp15
    user: umcg-genomescan-ateambot
    type: notification_webhooks
    analysis_phases: [PullAndProcessGsRawData, PullGsAnalysisData, ProcessGsAnalysisData, startDragenPipeline, startPipeline, startPostDragenPipeline, startNextflowDragenPipeline, pipeline, calculateProjectMd5s]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: dat05
    user: umcg-genomescan-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk_and_gd-ngs-dataverwerking
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-labgnkbh group
  ######################################################################################################################
  - group: umcg-labgnkbh
    lfs: tmp05
    user: umcg-labgnkbh-ateambot
    type: notification_webhooks
    analysis_phases: [demultiplexing]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-labgnkbh
    lfs: tmp15
    user: umcg-labgnkbh-ateambot
    type: notification_webhooks
    analysis_phases: [demultiplexing]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-labgnkbh
    lfs: dat45
    user: umcg-labgnkbh-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk_and_labgnkbh
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-labgnkbh
    lfs: prm45
    user: umcg-labgnkbh-dm
    type: notification_webhooks
    analysis_phases: [copyRawDataToPrm]
    notification_target: hpc-helpdesk_and_labgnkbh
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-patho group
  ######################################################################################################################
  - group: umcg-patho
    lfs: dat35
    user: umcg-patho-dm
    type: notification_webhooks
    analysis_phases: [moveAndCheckSamplesheets]
    notification_target: hpc-helpdesk_and_patho
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-patho
    lfs: prm35
    user: umcg-patho-dm
    type: notification_webhooks
    analysis_phases: [copyBclDataToPrm]
    notification_target: hpc-helpdesk_and_patho
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-lab group
  ######################################################################################################################
  - group: umcg-lab
    lfs: tmp05
    user: umcg-lab-ateambot
    type: notification_webhooks
    analysis_phases: [moveSequencingData]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-lab
    lfs: tmp15
    user: umcg-lab-ateambot
    type: notification_webhooks
    analysis_phases: [moveSequencingData]
    notification_target: hpc-helpdesk
    machines: "{{ groups['user_interface'] }}"
...
