---
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure:
  ######################################################################################################################
  # umcg-atd group
  ######################################################################################################################
  - group: umcg-atd
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['trendanalysis']['tmp']) 
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['NGS_RNA']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: dat05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['dat']
            | union(analysis_folders['trendanalysis']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-atd
    lfs: prm05
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['prm']
            | union(analysis_folders['NGS_RNA']['prm'])
            | union(analysis_folders['trendanalysis']['prm']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gd group
  ######################################################################################################################
  - group: umcg-gd
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['trendanalysis']['tmp'])
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['NGS_RNA']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: dat05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['dat']
            | union(analysis_folders['trendanalysis']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gd
    lfs: prm05
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-gd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['prm']
            | union(analysis_folders['NGS_RNA']['prm'])
            | union(analysis_folders['trendanalysis']['prm']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gst group
  ######################################################################################################################
  - group: umcg-gst
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gst-dm
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp'])
            | union(analysis_folders['nf_ngs_dna']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gst
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gst-dm
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gst
    lfs: dat05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gst-dm
    subfolders: "{{ analysis_folders['GsRawData']['dat']
            | union(analysis_folders['GsAnalysisData']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-genomescan group
  ######################################################################################################################
  - group: umcg-genomescan
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-genomescan-dm
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp'])
            | union(analysis_folders['nf_ngs_dna']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-genomescan-dm
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: dat05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-genomescan-dm
    subfolders: "{{ analysis_folders['GsRawData']['dat']
            | union(analysis_folders['GsAnalysisData']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-lab group
  ######################################################################################################################
  - group: umcg-lab
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-lab-dm
    subfolders:
      - logs
      - sequencers
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-lab
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-lab-dm
    subfolders:
      - logs
      - sequencers
    machines: "{{ groups['user_interface'] }}"
  ######################################################################################################################
  # umcg-labgnkbh group
  ######################################################################################################################
  - group: umcg-labgnkbh
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-labgnkbh-dm
    subfolders: "{{ analysis_folders['nf_ngs_dna-demultiplexing']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-labgnkbh
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-labgnkbh-dm
    subfolders: "{{ analysis_folders['nf_ngs_dna-demultiplexing']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-labgnkbh
    lfs: dat45
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-labgnkbh-dm
    subfolders: "{{ analysis_folders['nf_ngs_dna-demultiplexing']['dat'] }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-labgnkbh
    lfs: prm45
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-labgnkbh-dm
    subfolders: "{{ analysis_folders['nf_ngs_dna-demultiplexing']['prm'] }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-patho group
  ######################################################################################################################
  - group: umcg-patho
    lfs: tmp05
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-patho-dm
    subfolders: "{{ analysis_folders['BclDataToPrm']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-patho
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-patho-dm
    subfolders: "{{ analysis_folders['BclDataToPrm']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-patho
    lfs: dat35
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-patho-dm
    subfolders: "{{ analysis_folders['BclDataToPrm']['dat'] }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-patho
    lfs: prm35
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-patho-dm
    subfolders: "{{ analysis_folders['BclDataToPrm']['prm'] }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-pgx group
  ######################################################################################################################
  - group: umcg-pgx
    lfs: tmp15
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-pgx-dm
    subfolders: "{{ analysis_folders['PGx']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-pgx
    lfs: prm05
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-pgx-dm
    subfolders: "{{ analysis_folders['PGx']['prm'] }}"
    machines: "{{ groups['chaperone'] }}"
...
