---
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure:
  ######################################################################################################################
  # umcg-atd group
  ######################################################################################################################
  - group: umcg-atd
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-ateambot
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-ateambot
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-atd
    lfs: dat06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['dat']
            | union(analysis_folders['trendanalysis']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-atd
    lfs: prm06
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-atd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['prm']
            | union(analysis_folders['NGS_RNA']['prm'])
            | union(analysis_folders['trendanalysis']['prm']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gd group
  ######################################################################################################################
  - group: umcg-gd
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gd-ateambot
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gd-ateambot
    subfolders: "{{ analysis_folders['ConcordanceCheck']['tmp']
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['trendanalysis']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gd
    lfs: dat06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['dat']
            | union(analysis_folders['trendanalysis']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gd
    lfs: prm06
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-gd-dm
    subfolders: "{{ analysis_folders['ConcordanceCheck']['prm']
            | union(analysis_folders['NGS_RNA']['prm'])
            | union(analysis_folders['trendanalysis']['prm']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gsad group
  ######################################################################################################################
  - group: umcg-gsad
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gsad-ateambot
    subfolders: "{{ analysis_folders['AGCT']['tmp']
            | union(analysis_folders['GAP']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gsad
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gsad-ateambot
    subfolders: "{{ analysis_folders['AGCT']['tmp']
            | union(analysis_folders['GAP']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gsad
    lfs: dat06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gsad-dm
    subfolders: "{{ analysis_folders['AGCT']['dat']
            | union(analysis_folders['GAP']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gsad
    lfs: prm06
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-gsad-dm
    subfolders: "{{ analysis_folders['AGCT']['prm']
            | union(analysis_folders['GAP']['prm']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gap group
  ######################################################################################################################
  - group: umcg-gap
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gap-ateambot
    subfolders: "{{ analysis_folders['AGCT']['tmp']
            | union(analysis_folders['GAP']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gap
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gap-ateambot
    subfolders: "{{ analysis_folders['AGCT']['tmp']
            | union(analysis_folders['GAP']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gap
    lfs: dat06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gap-dm
    subfolders: "{{ analysis_folders['AGCT']['dat']
            | union(analysis_folders['GAP']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-gap
    lfs: prm06
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-gap-dm
    subfolders: "{{ analysis_folders['AGCT']['prm']
            | union(analysis_folders['GAP']['prm']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-gst group
  ######################################################################################################################
  - group: umcg-gst
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gst-ateambot
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gst
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gst-ateambot
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-gst
    lfs: dat06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-gst-dm
    subfolders: "{{ analysis_folders['GsRawData']['dat']
            | union(analysis_folders['GsAnalysisData']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-genomescan group
  ######################################################################################################################
  - group: umcg-genomescan
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-genomescan-ateambot
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-genomescan-ateambot
    subfolders: "{{ analysis_folders['GsRawData']['tmp']
            | union(analysis_folders['NGS_RNA']['tmp'])
            | union(analysis_folders['nf_ngs_dna']['tmp'])
            | union(analysis_folders['GsAnalysisData']['tmp']) }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-genomescan
    lfs: dat06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-genomescan-dm
    subfolders: "{{ analysis_folders['GsRawData']['dat']
            | union(analysis_folders['GsAnalysisData']['dat']) }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-lab group
  ######################################################################################################################
  - group: umcg-lab
    lfs: tmp06
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-lab-ateambot
    subfolders:
      - logs
      - sequencers
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-lab
    lfs: tmp16
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-lab-ateambot
    subfolders:
      - logs
      - sequencers
    machines: "{{ groups['user_interface'] }}"
  ######################################################################################################################
  # umcg-labgnkbh group
  ######################################################################################################################
  - group: umcg-labgnkbh
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-labgnkbh-ateambot
    subfolders: "{{ analysis_folders['NGS_Demultiplexing']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-labgnkbh
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-labgnkbh-ateambot
    subfolders: "{{ analysis_folders['NGS_Demultiplexing']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-labgnkbh
    lfs: dat46
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-labgnkbh-dm
    subfolders: "{{ analysis_folders['NGS_Demultiplexing']['dat'] }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-labgnkbh
    lfs: prm46
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-labgnkbh-dm
    subfolders: "{{ analysis_folders['NGS_Demultiplexing']['prm'] }}"
    machines: "{{ groups['chaperone'] }}"
  ######################################################################################################################
  # umcg-patho group
  ######################################################################################################################
  - group: umcg-patho
    lfs: tmp06
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-patho-ateambot
    subfolders: "{{ analysis_folders['BclDataToPrm']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-patho
    lfs: tmp16
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-patho-ateambot
    subfolders: "{{ analysis_folders['BclDataToPrm']['tmp'] }}"
    machines: "{{ groups['user_interface'] }}"
  - group: umcg-patho
    lfs: dat36
    mode: "{{ MODE_2770_HARD }}"
    owner: umcg-patho-dm
    subfolders: "{{ analysis_folders['BclDataToPrm']['dat'] }}"
    machines: "{{ groups['chaperone'] }}"
  - group: umcg-patho
    lfs: prm36
    mode: "{{ MODE_2750_HARD }}"
    owner: umcg-patho-dm
    subfolders: "{{ analysis_folders['BclDataToPrm']['prm'] }}"
    machines: "{{ groups['chaperone'] }}"
...
