---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: 'cf'
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here for Lua or Lmod,
#       please make sure to add corresponding values in group_vars/all/*.yml
#
lua_version: '5.1.4.9'
lmod_version: '8.6.2'
easybuild_version: '4.8.0'
eb_user: umcg-envsync
eb_group: umcg-depad
group_module_versions:
  umcg-gd:
    NGS_Automated:
      default: 4.7.0  # Default NGS_Automated version.
    nf_ngs_dna: 1.4.0
    ConcordanceCheck: 2.2.1
    ngs-utils: 24.02.2
    vip: v9.2.0
    Trendanalysis: 2.1.0
  umcg-gap:
    NGS_Automated:
      default: 4.2.0
    GAP: 2.7.0
    AGCT: 1.3.0
    ngs-utils: 24.02.2
  umcg-genomescan:
    NGS_Automated:
      default: 4.7.0
    nf_ngs_dna: 1.4.0
    NGS_RNA: 4.1.3
    ngs-utils: 24.03.1
  umcg-atd:
    NGS_Automated:
      default: 4.7.0  # Default NGS_Automated version.
    nf_ngs_dna: 1.4.0
    ConcordanceCheck: 3.0.0
    ngs-utils: 24.02.2
    Trendanalysis: 2.1.0
  umcg-gsad:
    NGS_Automated:
      default: 4.3.1
    GAP: 2.7.0
    AGCT: 1.3.0
    ngs-utils: 24.02.2
  umcg-gst:
    NGS_Automated:
      default: 4.7.0
    nf_ngs_dna: 1.4.0
    NGS_RNA: 4.1.3
    ngs-utils: 24.02.2
  umcg-labgnkbh:
    NGS_Automated:
      default: 4.7.0
    ngs-utils: 24.02.2
    nf_ngs_dna: 1.4.0
  umcg-patho:
    NGS_Automated:
      default: 4.2.0
    ngs-utils: 24.03.1
  umcg-lab:
    NGS_Automated:
      default: 4.6.0
#
# Sources, software and reference data to install/fetch.
#
public_sources: []
private_sources: []
refdata: [
  'Prepkits',
]
static_easyconfigs:
  - 'c/cluster-utils/cluster-utils-v26.01.1-GCCcore-13.3.0.eb'
  - 'd/depad-utils/depad-utils-v26.04.3.eb'
chaperone_only_easyconfigs: "{{ all_easyconfigs | select('search', '(NGS_Automated-.*-bare|depad-utils-.*).eb') | list }}"
...
