---
- name: Create folder structure for extra EasyConfigs.
  ansible.builtin.file:
    dest: "{{ extra_easyconfigs_path }}"
    state: directory
    mode: "{{ MODE_2775_HARD }}"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Git clone main branch of custom EasyConfigs repo.
  ansible.builtin.git:
    clone: true
    depth: 1
    version: main  # Fetches "main" branch.
    repo: "{{ extra_easyconfigs_repo_url }}"
    dest: "{{ extra_easyconfigs_path }}"
    force: true
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"
...
