---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: hc
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here for Lua or Lmod,
#       please make sure to add corresponding values in group_vars/all/*.yml
#
lua_version: 5.5.1
luaposix_version: 36.3
lmod_version: 9.4.2
easybuild_version: 5.4.0
eb_user: umcg-envsync
eb_group: umcg-depad
#
# Sources, software and reference data to install/fetch.
#
public_sources: []
private_sources: []
refdata: [
  'dbSNP',
  '1000G',
  'NGS_DNA_Test-data/Agilent/',
  'NGS_DNA_Test-data/CADD/',
  'NGS_DNA_Test-data/gnomAD/',
  'NGS_DNA_Test-data/UMCG/',
  'CGD',
  'ClinVar',
  'Controls_Convading_XHMM',
  'GSAarray',
  'ManVarList',
  'GAVIN',
  'GeneNetwork',
  'HPO',
  'UMCG',
  'gonl',
  'inSilico',
  'snpEff-4.3',
]
static_easyconfigs:
  - 'c/cluster-utils/cluster-utils-v26.09.1-GCCcore-13.3.0.eb'
  - 'd/depad-utils/depad-utils-v26.04.3.eb'
  - 'j/Java/Java-17-LTS.eb'
  - 'j/Java/Java-25-LTS.eb'
...
