---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: vt
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here for Lua or Lmod,
#       please make sure to add corresponding values in group_vars/all/*.yml
#
lua_version: 5.5.1
luaposix_version: 36.3
lmod_version: 9.4.2
easybuild_version: 5.4.0
eb_user: umcg-envsync
eb_group: umcg-depad
#
# Sources, software and reference data to install/fetch.
#
public_sources: []
private_sources: []
refdata: []
static_easyconfigs:
  - 'b/BCFtools/BCFtools-1.19-GCCcore-11.3.0.eb'
  - 'c/cluster-utils/cluster-utils-v26.09.1-GCCcore-13.3.0.eb'
  - 'd/depad-utils/depad-utils-v26.04.3.eb'
  - 'h/hashdeep/hashdeep-4.4-20180907-18a6b5d-GCCcore-11.3.0.eb'
  - 'h/HDF5/HDF5-1.12.2-gompi-2022a.eb'
  - 'h/htop/htop-3.2.1-GCCcore-11.3.0.eb'
  - 'j/Java/Java-11-LTS.eb'
  - 'm/make/make-4.3-GCCcore-11.3.0.eb'
  - 'r/R/R-4.2.2-foss-2022a-bare.eb'
  - 's/SAMtools/SAMtools-1.19.2-GCCcore-11.3.0.eb'
  - 'v/VEP/VEP-107-GCC-11.3.0.eb'
...
